PayPal/Models/PayPalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;

namespace PayPal.Models
{
    public class PayPalModel
    {
        public string cmd { get; set; }
        public string business { get; set; }
        public string no_shipping { get; set; }
        public string @return { get; set; }
        public string cancel_return { get; set; }
        public string notify_url { get; set; }
        public string currency_code { get; set; }
        public string item_name { get; set; }
        public string amount { get; set; }
        public string actionURL { get; set; }

        public PayPalModel(bool useSandbox)
        {
            this.cmd = "_xclick";
            this.business = ConfigurationManager.AppSettings["business"];
            this.cancel_return = ConfigurationManager.AppSettings["cancel_return"];
            this.@return = ConfigurationManager.AppSettings["return"];
            if (useSandbox)
            {
                this.actionURL = ConfigurationManager.AppSettings["test_url"];
            }
            else
            {
                this.actionURL = ConfigurationManager.AppSettings["Prod_url"];
            }
            // We can add parameters here, for example OrderId, CustomerId, etc....
            this.notify_url = ConfigurationManager.AppSettings["notify_url"];
            // We can add parameters here, for example OrderId, CustomerId, etc....
            this.currency_code = ConfigurationManager.AppSettings["currency_code"];
        }
    }
}

PayPal/Controllers/PayPalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using PayPal.Models;

namespace PayPal.Controllers
{
    public class PayPalController : Controller
    {
        //
        // GET: /PayPal/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ValidateCommand(string product, string totalPrice)
        {
            bool useSandbox = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSandbox"]);
            var paypal = new PayPalModel(useSandbox);

            paypal.item_name = product;
            paypal.amount = totalPrice;
            return View(paypal);
        }

        public ActionResult RedirectFromPaypal()
        {
            return View();
        }

        public ActionResult CancelFromPaypal()
        {
            return View();
        }

        public ActionResult NotifyFromPaypal()
        {
            return View();
        }


    }
}

PayPal/Views/PayPal/CancelFromPaypal.cshtml
@{
    ViewBag.Title = "CancelFromPaypal";
}

<h2>CancelFromPaypal</h2>

PayPal/Views/PayPal/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("ValidateCommand", "PayPal"))
{
    <div>
        <table >
            <tr>
                <td>
                    product Name:
                </td>
                <td>
                    <input type="text" name="product" value="PayPal Demo test" readonly />
                </td>
            </tr>
            <tr>
                <td>
                   Total Price:
                </td>
                <td>
                   <input type="text" name="totalPrice" value="200" readonly /> $
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <input type="submit" name="btnConfirm" value="Pay with Paypal" />
                </td>
            </tr>
        </table>
    </div>
}

PayPal/Views/PayPal/NotifyFromPaypal.cshtml
@{
    ViewBag.Title = "NotifyFromPaypal";
}

<h2>NotifyFromPaypal</h2>

PayPal/Views/PayPal/RedirectFromPaypal.cshtml
@{
    ViewBag.Title = "RedirectFromPaypal";
}

<h2>RedirectFromPaypal</h2>

PayPal/Views/PayPal/ValidateCommand.cshtml
@model PayPal.Models.PayPalModel

@{
    ViewBag.Title = "ValidateCommand";
}


    <form id="hiddenform" action=@Model.actionURL>
    @Html.HiddenFor(model => model.cmd)
    @Html.HiddenFor(model => model.business)
    @Html.HiddenFor(model => model.no_shipping)
    @Html.HiddenFor(model => model.@return)
    @Html.HiddenFor(model => model.cancel_return)
    @Html.HiddenFor(model => model.notify_url)
    @Html.HiddenFor(model => model.currency_code)
    @Html.HiddenFor(model => model.item_name)
    @Html.HiddenFor(model => model.amount)
    </form>

    <p style="text-align: center">
        <h3>
            Connecting to Paypal , please wait ...

        </h3>
    </p>

 @Scripts.Render("~/bundles/jquery")

<script type="text/javascript" language="javascript">
    $(this.document).ready(function () {
        var form = $("form");
        form.submit();
    });   
</script>

PayPal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>